Add support for scaling seating plans
mintopia/control pull request #30
Opened 2024-09-04 16:44 UTC by t3rminalV

When creating larger seating plans, the default scale of the grid means that the plan ends up quite big.

Added a percentile-based scale which can scale the layout grid down (or up) to help with larger layouts.

2024-09-05 12:53 UTC, mintopia requested changes
We shouldn't be fetching the image to get its size every time we render the plan. It should be determined either once and cached for a long TTL or in the backend when the image is set.

2024-09-05 12:53 UTC, mintopia commented on resources/views/admin/events/seats.blade.php
> +                                       min-height: {{ getimagesize($plan->image_url)[1] }}px"
We shouldn't be fetching the image to get its size when rendering the plan. Can we move this to when the image is updated on the backend and storing it alongside the plan?

2024-09-05 23:06 UTC, t3rminalV commented on resources/views/admin/events/seats.blade.php
> +                                       min-height: {{ getimagesize($plan->image_url)[1] }}px"
Have stored the image dimensions in the db table on seating plan save and then calling those instead of on each page load.

2024-09-06 08:34 UTC, mintopia approved these changes

2024-09-06 08:34 UTC, merged